### ISSUE TITLE
Data is lost after Encryption from UnEncrypted Database

### ISSUE THREAD

**Issue by raveesh08** [commonsguy/cwac-saferoom#65] opened 2019-09-18 09:41 UTC
i have UnEncrypted room db with version v1
i tried to upgrade to version v2 via room migration

i added new column in entity class apart from my earlier columns, also altering table during migration by adding new column.

```
@ColumnInfo(name="RubberStamp",typeAffinity = ColumnInfo.BLOB)
    private byte[] RubberStamp;
```

Migration callback works perfect without using`SQLCipherUtils.encrypt` & `openHelperFactory(factory)` with existing database

but when same code is used with `SQLCipherUtils.encrypt` & `openHelperFactory(factory)` , room creates new Database/tables with version2  `onCreate` is called, not the migration code. all old will be lost.

```
@Database(entities =
        {
                Article.class
        },
        version = 2,exportSchema = false)
private static final String      DB_NAME = "mydb.db";
    private static       APPDatabase INSTANCE;
    public abstract      APPDao      appDao();
    private final static SafeHelperFactory.Options options = SafeHelperFactory.Options.builder().build();
    private final static Editable passPhrase=new SpannableStringBuilder("mypassword");

    private final static SafeHelperFactory factory=SafeHelperFactory.fromUser(passPhrase,options);


public static APPDatabase getDatabase(Context mContext)
    {
        if(INSTANCE==null)
        {
            INSTANCE=BuildDatabase(mContext);
        }
        return INSTANCE;
    }


private static APPDatabase BuildDatabase(Context mContext)
    {
        
        SQLCipherUtils.State sqlCipherUtils= SQLCipherUtils.getDatabaseState(mContext,APPDirectories.DATABASE_PATH+DB_NAME);
        if(sqlCipherUtils==SQLCipherUtils.State.UNENCRYPTED)
        {
            try
            {
                Log.e("Encryption","Started");
                SQLCipherUtils.encrypt(mContext,new File(APPDirectories.DATABASE_PATH+DB_NAME),passPhrase.toString().toCharArray());
                Log.e("Encryption","Finished");
            }
            catch (IOException e)
            {
                e.printStackTrace();
                Log.e("init","Error in DB Encryption");
            }
        }

        return Room.databaseBuilder(mContext,APPDatabase.class,APPDirectories.DATABASE_PATH+DB_NAME)
                .openHelperFactory(factory)
               
                .allowMainThreadQueries()
                .addCallback(new Callback()
                {
                    @Override
                    public void onCreate(@NonNull SupportSQLiteDatabase db)
                    {
                        Log.e("onCreate","Called");
                         //super.onCreate(db);
                    }

                    @Override
                    public void onOpen(@NonNull SupportSQLiteDatabase db)
                    {
                        Log.e("Version",String.valueOf(db.getVersion()));

                        //super.onOpen(db);
                    }
                })
                .addMigrations(new Migration(1,2)
                {
                    @Override
                    public void migrate(@NonNull SupportSQLiteDatabase database)
                    {
                        Log.e("Migration","Migration Called");
                        String query="ALTER TABLE Articles ADD COLUMN 'RubberStamp' BLOB DEFAULT NULL;";
                        try
                        {
                            database.execSQL(query);
                        }
                        catch (Exception ex)
                        {
                            
                        }
                    }
                })
                .build();
    }
```

**Kidnly give me solution as soon as possible**

please host some sample apps.

**Comment by commonsguy** [comment] 2019-09-18 10:54
> onCreate is called not the migration code

There is no `onCreate()` in [a `Migration`](https://developer.android.com/reference/androidx/room/migration/Migration), so I do not know what you mean by this.

> Migration callback works perfect with doing SQLCipherUtils.encrypt & openHelperFactory(factory)

You seem to be using `SQLCipherUtils.encrypt()` and `openHelperFactory(factory)` in the code in the question. I do not know what the difference is between what you believe works and what you believe does not work. And, I do not know if the code that you included in this issue works or does not work.

**Comment by raveesh08** [comment] 2019-09-18 11:10
Sir onCreate is  Room Callback. this callback is called whenever new Database is created by Room or if it opens an Existing Database.

```
Room.databaseBuilder(x,x,x)
.addCallback(new Callback()
                {
                    @Override
                    public void onCreate(@NonNull SupportSQLiteDatabase db)
                    {
                        
                    }
                    @Override
                    public void onOpen(@NonNull SupportSQLiteDatabase db)
                    {
                        
                    }
                })
                .addMigrations(new Migration(1,2)
               .build();
```

**Comment by commonsguy** [comment] 2019-09-18 11:12
`onCreate()` is called when the database is created *for the first time*. See [the documentation](https://developer.android.com/reference/androidx/room/RoomDatabase.Callback.htmlonCreate(androidx.sqlite.db.SupportSQLiteDatabase)). It will not be called for a migration, as the database already exists.

**Comment by raveesh08** [comment] 2019-09-18 11:14
yes exactly what i am also saying.. if i use encryption for existing database onCreate is being called..

**Comment by raveesh08** [comment] 2019-09-18 11:26
let me explain step by step
**New Database case**
1. Use `openHelperFactory(factory)` with password
2. `onCreate` is called (only for First time creation)
3. `onOpen` is called
4. subsequent Database connection works fine with encryption and decryption. 
5. Everything is fine

**Existing Database case**
1. check whether Database encrypted or not
2. if not encrypted then encrypt with password
3. Use `openHelperFactory(factory)` with password
4. `.addMigrations(new Migration(1,2)`  supposed to be called but it doesn't call this
**problem is here**
4. `onCreate` is called again (even though database already exists) with database version 2

**please correct me if i am following wrong method.**

**Comment by commonsguy** [comment] 2019-09-18 12:14
What you are describing should work. I already have a test case for migrations, but I do not have a test case for encrypting a database and then immediately triggering a migration. I will work on a test case for that this weekend. If the test case fails, I can try to fix the bug. If the test case succeeds, you will be able to see what I did and see if you can adjust your code to match mine.

**Comment by raveesh08** [comment] 2019-09-18 12:19
Thank you. if possible please add in the openHelper itself to encrypt if not encrypted earlier.

**Comment by commonsguy** [comment] 2019-09-21 16:59
I added [a test of encrypting an existing database, then migrating it](https://github.com/commonsguy/cwac-saferoom/blob/master/saferoom/src/androidTest/java/com/commonsware/cwac/saferoom/test/room/migratecrypt/MigrateCryptTest.java). The test works fine.

At this point, I need either:

- A complete project that can reproduce the problem, or
- A similar test case that can reproduce the problem, or
- If the test crashes in your environment, the details of that environment (e.g., library version, device that you are testing on), or
- **Detailed** instructions on how I can modify this test case to reproduce the problem

**Comment by raveesh08** [comment] 2019-09-23 04:17
Hi Thank you,
I will work on it this week.
i just noticed one small difference that you are using 2 different Abstract Class `TestV1Database` & `TestV2Database` in my case Abstract Class is same.

**Comment by commonsguy** [comment] 2019-09-23 10:29
From Room's standpoint, the name of the `RoomDatabase` class should not matter.

**Comment by raveesh08** [comment] 2019-09-27 05:16
Hi this is my code before upgradation
see my next comment for upgradation code....

```
@Entity(
        tableName = "Articles",
        primaryKeys = {"Article"}        
       )
final public class Article
{
    @NonNull
    @ColumnInfo(name = "Article")
    private String Article;
	
	public String getArticle() {
        return Article;
    }

    public void setArticle(String article) {
        Article = article;
    }
}

@Database(entities =
        {
                Article.class                
        },
        version = 1,exportSchema = false)
public abstract class APPDatabase extends RoomDatabase
{
    private static String TAG= APPDatabase.class.getSimpleName();
    private static final String      DATABASE_PATH = Environment.getExternalStorageDirectory()+"/data/Database/";
    private static final String      DB_NAME = "data.db";

    private static       APPDatabase INSTANCE;
    public abstract      APPDao      appDao();
    
    public static APPDatabase getDatabase(Context mContext)
    {
        if(INSTANCE==null)
        {
            INSTANCE=BuildDatabase(mContext);
        }
        return INSTANCE;
    }

    private static APPDatabase BuildDatabase(Context mContext)
    {
      
        return Room.databaseBuilder(mContext,APPDatabase.class,DATABASE_PATH+DB_NAME)                  
                .allowMainThreadQueries()
                .addCallback(new Callback()
                {
                    @Override
                    public void onCreate(@NonNull SupportSQLiteDatabase db)
                    {
                        Log.e(TAG,"onCreate Called");
                        super.onCreate(db);
                    }

                    @Override
                    public void onOpen(@NonNull SupportSQLiteDatabase db)
                    {
                       Log.e(TAG ,"Version : "+String.valueOf(db.getVersion()));
                       super.onOpen(db);
                    }
                })                            
                .build();
    }

    @NonNull
    @Override
    protected SupportSQLiteOpenHelper createOpenHelper(DatabaseConfiguration config)
    {
        Log.e(TAG,"createOpenHelper Called");
        return null;
    }

    @NonNull
    @Override
    protected InvalidationTracker createInvalidationTracker()
    {
        return null;
    }

    @Override
    public void clearAllTables()
    {

    }
}
```

**Comment by raveesh08** [comment] 2019-09-27 05:23
upgradation code

@Entity(
        tableName = "Articles",
        primaryKeys = {"Article"}        
       )
final public class Article
{
    @NonNull
    @ColumnInfo(name = "Article")
    private String Article;
	
@ColumnInfo(name="RubberStamp",typeAffinity = ColumnInfo.BLOB)
    private byte[] RubberStamp;

	public String getArticle() {
        return Article;
    }

    public void setArticle(String article) {
        Article = article;
    }

public byte[] getRubberStamp() {
        return RubberStamp;
    }

    public void setRubberStamp(byte[] rubberStamp) {
        RubberStamp = rubberStamp;
    }
}

@Database(entities =
        {
                Article.class                
        },
        version = 2,exportSchema = false)
public abstract class APPDatabase extends RoomDatabase
{
    private static String TAG= APPDatabase.class.getSimpleName();
    private static final String      DATABASE_PATH = Environment.getExternalStorageDirectory()+"/data/Database/";
    private static final String      DB_NAME = "data.db";

    private static       APPDatabase INSTANCE;
    public abstract      APPDao      appDao();
    private final static SafeHelperFactory.Options options = SafeHelperFactory.Options.builder().setClearPassphrase(false).build();
    private final static Editable passPhrase = new SpannableStringBuilder("password");

    private final static SafeHelperFactory factory=SafeHelperFactory.fromUser(passPhrase,options);

    public static APPDatabase getDatabase(Context mContext)
    {
        if(INSTANCE==null)
        {
            INSTANCE=BuildDatabase(mContext);
        }
        return INSTANCE;
    }

    private static APPDatabase BuildDatabase(Context mContext)
    {        
        SQLCipherUtils.State sqlCipherUtils= SQLCipherUtils.getDatabaseState(mContext,DATABASE_PATH+DB_NAME);
        if(sqlCipherUtils==SQLCipherUtils.State.UNENCRYPTED)
        {
            try
            {
                Log.e(TAG,"DB Encryption Started");
                SQLCipherUtils.encrypt(mContext,new File(DATABASE_PATH+DB_NAME),passPhrase.toString().toCharArray());
                Log.e(TAG,"DB Encryption Finished");                               
            }
            catch (Exception ex)
            {
                ex.printStackTrace();
                Log.e(TAG,"Error DB in Encryption : "+ex.toString());                
            }
        }

        return Room.databaseBuilder(mContext,APPDatabase.class,DATABASE_PATH+DB_NAME)
                .openHelperFactory(factory)                
                .allowMainThreadQueries()
                .addCallback(new Callback()
                {
                    @Override
                    public void onCreate(@NonNull SupportSQLiteDatabase db)
                    {
                        Log.e(TAG,"onCreate Called");
                        super.onCreate(db);
                    }

                    @Override
                    public void onOpen(@NonNull SupportSQLiteDatabase db)
                    {
                        Log.e(TAG ,"Version : "+String.valueOf(db.getVersion()));
                        super.onOpen(db);
                    }
                })
                .addMigrations(new Migration(1,2)
                {
                    @Override
                    public void migrate(@NonNull SupportSQLiteDatabase database)
                    {
                        Log.e(TAG,"Migration 2 Started");
                        try
                        {
                            String query=   "ALTER TABLE Articles ADD COLUMN 'RubberStamp' BLOB DEFAULT NULL;";
                            database.execSQL(query);
                        }
                        catch (Exception ex)
                        {
                            
                        }
                        Log.e(TAG,"Migration Finished");
                    }
                })                
                .build();
    }

    @NonNull
    @Override
    protected SupportSQLiteOpenHelper createOpenHelper(DatabaseConfiguration config)
    {
        Log.e(TAG,"createOpenHelper Called");
        return null;
    }

    @NonNull
    @Override
    protected InvalidationTracker createInvalidationTracker()
    {
        return null;
    }

    @Override
    public void clearAllTables()
    {

    }
}

**Comment by commonsguy** [comment] 2019-09-27 10:51
I need either:

- A complete project that can reproduce the problem (or 2 if you cannot reproduce it with just a single project), or
- A similar test case that can reproduce the problem, or
- If the test crashes in your environment, the details of that environment (e.g., library version, device that you are testing on), or
- **Detailed** instructions on how I can modify this test case to reproduce the problem

**Comment by raveesh08** [comment] 2019-09-27 11:22
ok.
Can you check once using same Room Abstract Class instead of V1 and V2

**Comment by commonsguy** [comment] 2019-09-27 11:54
I cannot do that in an instrumented test. The schema version is part of the `@Database` annotation, and I cannot replace it at runtime. That is why I needed two `RoomDatabase` classes. Similarly, I needed two `@Entity` classes so that I could introduce a schema change.

Your scenario will also require two `RoomDatabase` classes and two entity classes &mdash; it is just that in normal development, those two versions will be the same file, changing over time. There is no practical way that I can think of to do that in an automated test, other than by the approach that I took.

A way for you to provide a reproducible set of code that mimics your situation is:

- Create a project
- In that project, implement the code that represents your "before the encrypt-and-migrate" state
- Make a copy of that project
- In the copy, modify the code to handle your encrypt-and-migrate scenario (notably, do not change class names, `applicationId`, etc.)
- Confirm that if you run the first project, then run the second project, that the problem occurs
- ZIP up both projects (note: you may need to delete the `build/` and `app/build/` directories in the ZIP files to get them small enough)
- Attach those ZIP files to a comment on this issue, preferably with some instructions

If you do not do that, I might eventually try it myself, but that may not be for several weeks.

**Comment by commonsguy** [comment] 2019-10-13 16:22
@raveesh08 I recommend that you replace:

    String query="ALTER TABLE Articles ADD COLUMN 'RubberStamp' BLOB DEFAULT NULL;";

with:

    String query="ALTER TABLE Articles ADD COLUMN 'RubberStamp' BLOB;";

That will have your table match what Room expects. With Room 2.2.0, you could try using `defaultValue` in your `@ColumnInfo` annotation, if you want the SQL to use a `DEFAULT` value.

In terms of reproducing your problem, here is my latest attempt:

[RoomMigration.zip](https://github.com/commonsguy/cwac-saferoom/files/3721946/RoomMigration.zip)

You will find three projects in that directory:

- `V1/Notes/` contains a small Room project, including a "test" that saves a couple of rows to a database file
- `V2/Notes/` contains the same project with a schema change and a test that demonstrates upgrading the schema via a `Migration`
- `V2Encrypted/Notes/` contains a variant of V2 that encrypts the V1 database, then opens it using Room and `SafeHelperFactory`

All tests succeed, including the one that does the encrypt-then-migrate scenario.

At this point, I am closing this ticket as not reproducible. If you can give me a **complete** set of code and instructions for reproducing your problem, I will be happy to take a look at it.

**Closed by commonsguy** 2019-10-13 16:22 UTC
