### ISSUE TITLE
Compile Error Return code 1 for dex process when launching to AVD or real device

### ISSUE THREAD

**Issue by whizzthrough** [commonsguy/cwac-saferoom#19] opened 2018-03-26 10:57 UTC
Hi,

I have a weird bug. Version 0.1.1 is the last that works with my project.

`compile "com.commonsware.cwac:saferoom:0.1.1"`

If I put any version above (0.1.2, etc...) I can compile but when I want to deploy to AVD or real phone I get **Error Return code 1 for dex process** and te following log stack.

`
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':3dp-chief:transformClassesWithDexForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex '/home/yoram/.android/build-cache/19a3c2dcad9df70a3845d990cf8f3daecd793b73/output/jars/classes.jar' to '/home/yoram/dev/git/NetfeverTeam/3dprotect/3dprotect-android/3dp-chief/build/intermediates/transforms/dex/debug/folders/1000/10/classes_f09306282152a7d0b15c4e2280bfe42b07f86c2d'
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
	at sun.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	... 33 more
Caused by: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex '/home/yoram/.android/build-cache/19a3c2dcad9df70a3845d990cf8f3daecd793b73/output/jars/classes.jar' to '/home/yoram/dev/git/NetfeverTeam/3dprotect/3dprotect-android/3dp-chief/build/intermediates/transforms/dex/debug/folders/1000/10/classes_f09306282152a7d0b15c4e2280bfe42b07f86c2d'
	at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:453)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 48 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Unable to pre-dex '/home/yoram/.android/build-cache/19a3c2dcad9df70a3845d990cf8f3daecd793b73/output/jars/classes.jar' to '/home/yoram/dev/git/NetfeverTeam/3dprotect/3dprotect-android/3dp-chief/build/intermediates/transforms/dex/debug/folders/1000/10/classes_f09306282152a7d0b15c4e2280bfe42b07f86c2d'
	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:147)
	at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:408)
	... 51 more
Caused by: java.lang.RuntimeException: Unable to pre-dex '/home/yoram/.android/build-cache/19a3c2dcad9df70a3845d990cf8f3daecd793b73/output/jars/classes.jar' to '/home/yoram/dev/git/NetfeverTeam/3dprotect/3dprotect-android/3dp-chief/build/intermediates/transforms/dex/debug/folders/1000/10/classes_f09306282152a7d0b15c4e2280bfe42b07f86c2d'
	at com.android.build.gradle.internal.transforms.DexTransform$PreDexTask.call(DexTransform.java:521)
	at com.android.build.gradle.internal.transforms.DexTransform$PreDexTask.call(DexTransform.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at com.android.builder.utils.FileCache.doInterProcessLocked(FileCache.java:680)
	at com.android.builder.utils.FileCache.doLocked(FileCache.java:639)
	at com.android.builder.utils.FileCache.queryCacheEntry(FileCache.java:395)
	at com.android.builder.utils.FileCache.createFile(FileCache.java:290)
	at com.android.build.gradle.internal.transforms.DexTransform$PreDexTask.call(DexTransform.java:518)
	... 7 more
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at com.android.builder.utils.FileCache.doInterProcessLocked(FileCache.java:680)
	at com.android.builder.utils.FileCache.doLocked(FileCache.java:639)
	at com.android.builder.utils.FileCache.lambda$queryCacheEntry$10(FileCache.java:419)
	at com.android.builder.utils.FileCache.doInterProcessLocked(FileCache.java:678)
	... 11 more
Caused by: java.util.concurrent.ExecutionException: com.android.builder.utils.FileCache$FileCreatorException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at com.android.builder.utils.FileCache.doInterProcessLocked(FileCache.java:680)
	at com.android.builder.utils.FileCache.doLocked(FileCache.java:639)
	at com.android.builder.utils.FileCache.lambda$createFile$5(FileCache.java:282)
	at com.android.builder.utils.FileCache.lambda$null$9(FileCache.java:440)
	at com.android.builder.utils.FileCache.doInterProcessLocked(FileCache.java:678)
	... 14 more
Caused by: com.android.builder.utils.FileCache$FileCreatorException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at com.android.builder.utils.FileCache.lambda$createFile$0(FileCache.java:241)
	at com.android.builder.utils.FileCache.lambda$null$4(FileCache.java:285)
	at com.android.builder.utils.FileCache.doInterProcessLocked(FileCache.java:678)
	... 18 more
Caused by: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at com.android.builder.core.DexByteCodeConverter.dexInProcess(DexByteCodeConverter.java:180)
	at com.android.builder.core.DexByteCodeConverter.runDexer(DexByteCodeConverter.java:158)
	at com.android.builder.core.AndroidBuilder.preDexLibraryNoCache(AndroidBuilder.java:1464)
	at com.android.builder.internal.compiler.PreDexCache.preDexLibrary(PreDexCache.java:129)
	at com.android.builder.core.AndroidBuilder.preDexLibrary(AndroidBuilder.java:1415)
	at com.android.build.gradle.internal.transforms.DexTransform$PreDexTask.lambda$call$0(DexTransform.java:503)
	at com.android.builder.utils.FileCache.lambda$createFile$0(FileCache.java:239)
	... 20 more
Caused by: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.android.builder.core.DexByteCodeConverter.dexInProcess(DexByteCodeConverter.java:178)
	... 26 more
Caused by: com.android.ide.common.process.ProcessException: Return code 1 for dex process
	at com.android.builder.internal.compiler.DexWrapper$DexProcessResult.assertNormalExitValue(DexWrapper.java:117)
	at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:175)
	... 4 more

`

**Comment by commonsguy** [comment] 2018-03-26 11:17
I don't really have much of a way of helping with that, without a reproducible test case. If you create a scrap project and add SafeRoom 0.1.3 or higher to it, do you encounter the same issue?

**Comment by whizzthrough** [comment] 2018-03-26 11:37
If I build a simple project, just adding the dependency into build.gradle

I've create an empty project. Up to 0.1.1 you can deploy it, after you can't 

https://ufile.io/n18ro

I'm using gradle 4.6 and intellij 2017.3.5

**Comment by commonsguy** [comment] 2018-03-26 11:52
I don't use IntelliJ IDEA, nor Gradle 4.6, so probably the problem lies with compatibility with one of those.

I am not certain when I will get a chance to run experiments with this environment, though I will add it to my to-do list.

**Comment by whizzthrough** [comment] 2018-03-26 12:58
What version of Gradle is it suppose to work with?

**Comment by commonsguy** [comment] 2018-03-26 13:00
The project itself uses Gradle 4.1. I am not aware of any changes in Gradle 4.6 that would cause this problem, but I have not tried it.

**Comment by whizzthrough** [comment] 2018-03-26 13:43
For your info: Same problem with gradle 4.1. I'm guessing since Android Studio is based on intelliJ IDEA it should n't be a problem.

**Comment by commonsguy** [comment] 2018-03-26 13:49
I just created a brand-new Android Studio 3.0.1 project (which uses Gradle 4.1), added the necessary lines to `repositories` and `dependencies` for 0.3.2 per the project `README`, and I have no build problems. If this were a common problem, my guess is that somebody else would have complained before now, as it's been a while since I upgraded to AS 3.0.0 and the new Gradle build instructions (e.g., `api` instead of `compile`).

Right now, my evidence suggests that the problem is tied either to IDEA or your development environment.

You might try a command-line Gradle build, particularly with `--refresh-dependencies`, and see if that gives you different results. I will try to set aside some time to install IDEA and see if I can reproduce the problem, perhaps late this week.

**Comment by whizzthrough** [comment] 2018-03-26 20:54
I found a way to correct it, I need to modify my build.gradle by adding the following code

`
android {
    ...
    dexOptions{
        javaMaxHeapSize "4g"
    }
    ...
}

I'm not sure why though...

**Comment by commonsguy** [comment] 2018-03-26 21:05
Hmmmm... that allocates memory to the DEX generation process. SafeRoom isn't very big, and neither is Room or the stuff that Room depends upon. How much code the Room annotation processor generates depends on how many entities and stuff you define. While SafeRoom pulls in SQLCipher for Android, that is mostly native code, which is not part of the DEXing process.

If you had not used Room previously, and so you were adding SafeRoom plus SQLCipher for Android plus Room, it's possible that you just crossed some threshold based on the combined total of all your dependencies. If you already had Room... it's still possible, but it becomes a bit less likely, just because SafeRoom and SQLCipher for Android aren't that big.

Anyway, I'm glad to hear that you got it worked out! I'll close this issue.

**Closed by commonsguy** 2018-03-26 21:05 UTC
