### ISSUE TITLE
SQLiteException database is locked : BEGIN EXCLUSIVE

### ISSUE THREAD

**Issue by chla-android** [commonsguy/cwac-saferoom#16] opened 2018-02-12 08:23 UTC
Hello,

Sometimes, i got BEGIN EXCLUSIVE exception while using CWAC-saferoom librarie for our database (see complete trace below). 

While looking at the source code, i was wondering if there was not a problem with object lock on the Helper.java class because the method getWritableDatabase is synchronized to avoid multiple database creation but the getWrappedDb is not synchronized so you may create two wrappers on the same database.

```Helper.java java
SupportSQLiteDatabase getWritableSupportDatabase(char[] passphrase) {
      SQLiteDatabase db=super.getWritableDatabase(passphrase);

      return(getWrappedDb(db));
    }

    Database getWrappedDb(SQLiteDatabase db) {
      if (wrappedDb==null) {
        wrappedDb=new Database(db);
      }

      return(wrappedDb);
    }
```

Full exception traces

```text
01-22 11:27:57.893 24879-24879/? E/UncaughtExceptionFragment: [main] - onCreateView uncaughtException=net.sqlcipher.database.SQLiteException: database is locked: BEGIN EXCLUSIVE;
                                                                  at net.sqlcipher.database.SQLiteDatabase.native_execSQL(Native Method)
                                                                  at net.sqlcipher.database.SQLiteDatabase.execSQL(SQLiteDatabase.java:2265)
                                                                  at net.sqlcipher.database.SQLiteDatabase.beginTransactionWithListener(SQLiteDatabase.java:706)
                                                                  at net.sqlcipher.database.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:658)
                                                                  at com.commonsware.cwac.saferoom.Database.beginTransaction(Database.java:61)
                                                                  at android.arch.persistence.room.InvalidationTracker.internalInit(InvalidationTracker.java:153)
                                                                  at android.arch.persistence.room.RoomDatabase.internalInitInvalidationTracker(RoomDatabase.java:282)
                                                                  at com.android.database.Database_Impl.access$400(Database_Impl.java:21)
                                                                  at com.android.database.Database_Impl$1.onOpen(Database_Impl.java:72)
                                                                  at android.arch.persistence.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:101)
                                                                  at com.commonsware.cwac.saferoom.Helper$1.onOpen(Helper.java:81)
                                                                  at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:182)
                                                                  at com.commonsware.cwac.saferoom.Helper$OpenHelper.getWritableSupportDatabase(Helper.java:158)
                                                                  at com.commonsware.cwac.saferoom.Helper.getWritableDatabase(Helper.java:121)
                                                                  at android.arch.persistence.room.RoomDatabase.compileStatement(RoomDatabase.java:204)
```

**Comment by commonsguy** [comment] 2018-02-12 14:49
My code mirrors that of `FrameworkSQLiteOpenHelper`, the official implementation from Google that wraps the native `SQLiteDatabase`. It too does not use `synchronized` here.

Also, I am skeptical that `synchronized` here would help. There are two layers of synchronization needed, neither of which are at the level of the SafeRoom code:

1. We need synchronization in the `SQLiteDatabase` implementation that all of this wraps. That is handled by the native `SQLiteDatabase` and by the SQLCipher for Android implementation of `SQLiteDatabase`.

2. Consumers of a `SupportSQLiteOpenHelper` need to ensure that they are creating a singleton instance of `SupportSQLiteDatabase`. You appear to be using Room, and Room should be ensuring that it uses singleton instance of `SupportSQLiteDatabase`, assuming that you have a singleton `RoomDatabase` subclass.  Looking at the Room code, I do not see where they are synchronizing creation of the `SupportSQLiteDatabase`, though I am having some difficulty navigating all of their code and may be missing the relevant sections.

If you have a project that can reproduce this crash, I'd be happy to look at it and see if I can track down the problem.

If you are looking for a workaround, in your code that creates your singleton `RoomDatabase`, use `getOpenHelper().getWritableDatabase()` to force Room to create the `SupportSQLiteDatabase` inside your own synchronized code segment.

**Comment by commonsguy** [comment] 2018-02-12 15:19
After further review of the code, I'm more comfortable that we're doing the right thing. It is the job of `SQLiteOpenHelper` to ensure that it creates a single instance of `SQLiteDatabase`. SQLCipher's does, and I presume that the native implementation does as well. It is the job of `RoomDatabase` to ensure that it creates a single instance of `SQLiteOpenHelper`, and that seems to be done as part of instantiation. So, AFAICT, the only way to wind up with two `SQLiteDatabase` objects is to have two `RoomDatabase` objects.

So, I'm back to needing a reproducible test case in order to proceed further.

**Comment by commonsguy** [comment] 2018-07-07 21:22
Closing as not reproducible.

**Closed by commonsguy** 2018-07-07 21:22 UTC
