### ISSUE TITLE
Show database in DB browser for SQLite

### ISSUE THREAD

**Issue by miladsi90** [commonsguy/cwac-saferoom#58] opened 2019-06-19 06:37 UTC
I set my password "1234" and try to open it but i cant.
How can i set custom setting about algorithms and what algorithm does it use in cwac-saferoom.

![a](https://user-images.githubusercontent.com/31917346/59742128-28d59300-9282-11e9-9ba7-c178d151182a.png)

This is my configuration : 

```
    public static SensitiveDatabase getSensitiveDatabase(Context context) {

        if (INSTANCE == null) {


            EditText editText=new EditText(context);
            editText.setText("1234");
            SafeHelperFactory factory = SafeHelperFactory.fromUser(editText.getText());
            INSTANCE = Room.databaseBuilder(context, SensitiveDatabase.class, "sensitive.db")
                    .openHelperFactory(factory)
                    .build();

        }
        return INSTANCE;
    }
```

And can i open it with this way?

**Comment by commonsguy** [comment] 2019-06-19 11:21
SafeRoom does not use any algorithm, because SafeRoom does not perform any encryption. SQLCipher for Android does. SafeRoom is simply some glue code to allow SQLCipher for Android to be used by consumers of the `androidx.sqlite` interfaces, such as Room.

SafeRoom 0.x uses SQLCipher for Android 3.x. SafeRoom 1.x uses SQLCipher for Android 4.x. So, the version of SafeRoom that you are using determines the version of SQLCipher for Android that you are using. SafeRoom does not change any of the encryption from SQLCipher for Android's defaults.

If you wish to change those things:

- Review [the SQLCipher for Android documentation](https://www.zetetic.net/sqlcipher/sqlcipher-api/)
- Create a SQL script that executes your desired `PRAGMA` statements
- Pass that SQL script, as a string, to `fromUser()` or the `SafeHelperFactory` constructor as the second parameter (see https://github.com/commonsguy/cwac-saferoom#keeping-the-old-format for example)

**Comment by commonsguy** [comment] 2019-06-19 11:59
Oh, wait.

It just dawned on me that the `PRAGMA` statements for affecting the cryptography need to be in "pre-key" SQL, and what I provide is "post-key" SQL support. I will need to add an option to supply pre-key SQL to execute. I will work on that and will update this issue when it is ready.

**Comment by miladsi90** [comment] 2019-06-19 12:41
@commonsguy You mean I cannot open the file? What is your plan for this bug?

**Comment by commonsguy** [comment] 2019-06-19 12:54
> You mean I cannot open the file?

I have no idea. I did not create the file, and I did not use the tool that you are using (an indeterminate version of DB Browser on an indeterminate version of macOS, based on the screenshot). I am simply trying to answer your questions. You might:

- Look at your module's `build.gradle` file
- Look to see what version of SafeRoom you are using
- Use that to determine the major version of SQLCipher for Android that you are using (SafeRoom 0.x = SQLCipher 3.x, SafeRoom 1.x = SQLCipher 4.x)
- Try using those defaults in the version of DB Browser that you are trying to use

My [second comment](https://github.com/commonsguy/cwac-saferoom/issues/58#issuecomment-503530532) was in regards to "How can i set custom setting about algorithms".

> What is your plan for this bug?

You have not demonstrated that there is a bug in SafeRoom.

If you wish, you can follow [the contribution guidelines for filing bug reports](https://github.com/commonsguy/cwac-saferoom/blob/master/CONTRIBUTING.md#contributing-bug-reports) and provide:

- the Android OS version on which you are experiencing the problem
- the code necessary to reproduce the problem (this could be the repo's demo app, or it could be some demo project of yours that you publish)
- the steps necessary, using that code and that version of Android, to reproduce the problem

In your particular case, I would also need to know what version of DB Browser you are using.

Note that "the code necessary to reproduce the problem" needs to be more than the snippet in your question. At minimum, I would need your module's `build.gradle` file, so I know the version of SafeRoom that you are using and any other settings that might affect the resulting code.

**Comment by hannesa2** [comment] 2019-06-20 05:16
This was asked in the past https://github.com/commonsguy/cwac-saferoom/issues/44 and not really answered

**Comment by miladsi90** [comment] 2019-06-20 06:12
**Contributing Bug Reports**

Android OS vesion : 8 and 9
Version of [sqlitebrowser](https://github.com/sqlitebrowser/sqlitebrowser/): 3.11.0
OS : Ubuntu 16.04.6 LTS

`build.gradle` : 

```
    implementation  "android.arch.persistence.room:runtime:1.1.1"
    annotationProcessor  "android.arch.persistence.room:compiler:1.1.1"
    implementation "com.commonsware.cwac:saferoom:1.0.5"
```

As i wrote this is my room config : 

```
    public static SensitiveDatabase getSensitiveDatabase(Context context) {

        if (INSTANCE == null) {


            EditText editText=new EditText(context);
            editText.setText("1234");
            SafeHelperFactory factory = SafeHelperFactory.fromUser(editText.getText());
            INSTANCE = Room.databaseBuilder(context, SensitiveDatabase.class, "sensitive.db")
                    .openHelperFactory(factory)
                    .build();

        }
        return INSTANCE;
    }
```

**Comment by commonsguy** [comment] 2019-06-20 12:27
Attached is a sample project using SafeRoom. In the project root directory is `sensitive.db`, which is a database created using the sample app via the following steps:

1. Run the app (tested via Android Studio 3.4.1, deploying the app to a Pixel 2 running Android 9.0)
2. Click the Open Database button
3. Wait for the message at the top to turn to "Opened"
4. Click the Close Database button
5. Wait for the message at the top to turn to "Closed"
6. Copy the `sensitive.db` file from `/data/data/com.commonsware.mysaferoomtest/databases/` (tested via Android Studio's Device File Explorer)

This file opens fine using DB Browser on macOS. It does not open on DB Browser for Linux. This suggests that the problem is with DB Browser for Linux or the `libsqlcipher-dev` dependency.

I am going to close this issue as not reproducible, given that I can open a SafeRoom database in DB Browser on macOS. If you still feel that SafeRoom is somehow the cause of your difficulties, please do what I did here and [provide a complete sample project and a set of steps to reproduce the problem](https://github.com/commonsguy/cwac-saferoom/blob/master/CONTRIBUTING.md#contributing-bug-reports).

[MySafeRoomTest.zip](https://github.com/commonsguy/cwac-saferoom/files/3310339/MySafeRoomTest.zip)

**Closed by commonsguy** 2019-06-20 12:27 UTC

**Comment by tomaszkruzel** [comment] 2019-06-24 10:05
@miladsalimiiii not sure what you'd like to achieve. But if your goal is browsing the database while developing the app then on your development environment you could set empty string "" as the db password. Then your db won't be encrypted and you could browse it with Stetho. 

Use it only when necessary, because otherwise you may miss some encryption problems.

**Comment by miladsalimiiii** [comment] 2019-06-24 18:47
@tomaszkruzel , i could open my encrypted database in MAC OS , but i could not open it in Linux.
Thank you for your suggestion i used Stetho earlier .

**Comment by andrew-koster-** [comment] 2019-09-27 18:14
I'm using the basic encryption options directly from the library's Github readme:

```
val encryption = SafeHelperFactory(charArrayOf('f', 'o', 'o'))

db = Room.databaseBuilder(
        Util.application!!,
        AppDatabase::class.java,
        "AppDatabase"
)
        .openHelperFactory(encryption)
        .build()
```

I can't open the file with the SQLCipher version of DB Browser for SQLite. I enter the password "foo" and it just keeps asking me for the password again. I know that you didn't create SQLCipher or DB Browser for SQLite, but you must have some way of browsing encrypted databases that are created using your library, @commonsguy ?

**Comment by commonsguy** [comment] 2019-09-27 19:02
@andrew-koster- As I [commented earlier](https://github.com/commonsguy/cwac-saferoom/issues/58#issuecomment-504006040), I was able to use DB Browser for SQLite on macOS to open a database. Outside of that particular instance, I can't recall the last time that I needed to access an encrypted database from something other than the app itself. I am sorry if my particular development approach is atypical.

Other than that, make sure your database is closed before you try copying it, and if you see that there are multiple files (e.g., `db` and `wal` and stuff), copy all of them. And, if you can give me a project that reproduces a problem, I'll be happy to look at it.
